# Generated by Django 6.0.3 on 2026-03-16 01:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConteudoLista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo', models.CharField(max_length=200)),
                ('lista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.lista')),
            ],
        ),
    ]
